Bugfix: passing < 1900 dates to the iso_date filter now works
Fixes errors like this one:
ValueError: year=13 is before 1900; the datetime strftime() methods
require year >= 1900